select
  inst_id,
  NAME DGNAME,
  STATE,
  TYPE REDUNDANCY_LEVEL,
  SECTOR_SIZE,
  BLOCK_SIZE,
  ALLOCATION_UNIT_SIZE,
  COMPATIBILITY,
  DATABASE_COMPATIBILITY,
  TOTAL_MB/1024 as DG_TOTAL_SIZE,
  (TOTAL_MB-FREE_MB)/1024 as DG_USED_SIZE,
  FREE_MB/1024 as DG_FREE_SIZE
from 
  GV$ASM_DISKGROUP_STAT
order by 1,2
