---

- name: Performance collector playbook
  hosts: all
  gather_facts: no
  tasks:
    - name: Check if it's a VIOS
      stat:
        path: /usr/ios/cli/ioscli
      register: ioscli_result

    - name: Check if it's a AIX based OS
      stat:
        path: /usr/lib/boot/unix_64
      register: bos_mp

    - name: mpstat 
      command: mpstat -a 1 2
      poll: 02 
      register: mpstat
      when: bos_mp.stat.exists == True

    - name: lparstat_i
      command: lparstat -i
      poll: 02 
      register: lparstat_i
      when: bos_mp.stat.exists == True

    - name: lparstat_s
      command: lparstat 1 2
      register: lparstat_s
      when: bos_mp.stat.exists == True

    - name: netstat_s
      command: netstat -s
      register: netstat_s
      when: bos_mp.stat.exists == True

    - name: entstat
      entstat:
      register: entstat
