---

- name: Performance collector playbook
  hosts: all
  gather_facts: no
  tasks:
    - name: Check if it's a VIOS
      stat:
        path: /usr/ios/cli/ioscli
      register: ioscli_result

    - name: Check if it's a AIX based OS
      stat:
        path: /usr/lib/boot/unix_64
      register: bos_mp

    - name: smtctl_c
      command: smtctl
      poll: 02
      register: smtctl_c
      when: bos_mp.stat.exists == True

    - name: iostat_AIX
      command: iostat -DRTl 1 2
      register: iostat
      when: bos_mp.stat.exists == True

    - name: iostat_LINUX
      command: iostat -d -k -N -p ALL -t -x -y  1 2
      register: iostat
      when: bos_mp.stat.exists != True

    - name: lsdev_class
      command: lsdev -C -H -S a -F name:class:subclass:type
      poll: 02
      register: lsdev_class
      when: bos_mp.stat.exists == True

    - name: mpstat_AIX
      command: mpstat -a 1 2
      poll: 02 
      register: mpstat_AIX
      when: bos_mp.stat.exists == True

    - name: mpstat_LINUX
      command: mpstat -P ALL 1 2
      poll: 02
      register: mpstat_LINUX
      when: bos_mp.stat.exists != True

    - name: lparstat_i
      command: lparstat -i
      poll: 02 
      register: lparstat_i
      when: bos_mp.stat.exists == True

    - name: lparstat_s
      command: lparstat 1 2
      poll: 02 
      register: lparstat_s
      when: bos_mp.stat.exists == True

    - name: netstat_s
      command: netstat -s
      poll: 02 
      register: netstat_s
      when: bos_mp.stat.exists == True

    - name: entstat
      entstat:
      register: entstat
      poll: 02
      when: bos_mp.stat.exists == True

    - name: fcstat
      fcstat:
      register: fcstat
      poll: 02
      when: bos_mp.stat.exists == True

    - name: uname_a
      command: uname -a
      poll: 02 
      register: uname_a
